name: employee_communication_app
description: "Internal communication is the key to success in any organization. Employee apps help businesses with human resources initiatives, safety and compliance, employee training, benefits administration, and more. You can even use an employee self-service app for your staff to check pay stubs on their phones. Push notifications make it easy for organizations to notify employees about upcoming events and urgent scheduling changes. These such apps even work for crisis and emergency communication."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  cloud_firestore: ^4.13.6

  # UI Packages
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_local_notifications: ^16.2.0

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  permission_handler: ^11.1.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1

  # Web Support
  firebase_auth_web: ^5.8.12
  firebase_messaging_web: ^3.5.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/signin-illustration.jpg
    - assets/images/signup-illustration.jpg
    - assets/images/splash-illustration.jpg



  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700