// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAus_o9p2IhKHPnecp3mTQKxxWWf6i2F4',
    appId: '1:46439967773:web:4a4d3a4f3e2252845b6af4',
    messagingSenderId: '46439967773',
    projectId: 'employee-communication-a-e9d67',
    authDomain: 'employee-communication-a-e9d67.firebaseapp.com',
    storageBucket: 'employee-communication-a-e9d67.firebasestorage.app',
    measurementId: 'G-5CX64DEBT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnu6h-soj1UnF-2IZtRehhkLJMzjtZ6ng',
    appId: '1:46439967773:android:aecfae224da7788a5b6af4',
    messagingSenderId: '46439967773',
    projectId: 'employee-communication-a-e9d67',
    storageBucket: 'employee-communication-a-e9d67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCheDVmVE4ZfKfedmdOWTXjdNWmfBDFGGU',
    appId: '1:46439967773:ios:6d5b40030dccd9d45b6af4',
    messagingSenderId: '46439967773',
    projectId: 'employee-communication-a-e9d67',
    storageBucket: 'employee-communication-a-e9d67.firebasestorage.app',
    iosBundleId: 'com.example.employeeCommunicationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCheDVmVE4ZfKfedmdOWTXjdNWmfBDFGGU',
    appId: '1:46439967773:ios:6d5b40030dccd9d45b6af4',
    messagingSenderId: '46439967773',
    projectId: 'employee-communication-a-e9d67',
    storageBucket: 'employee-communication-a-e9d67.firebasestorage.app',
    iosBundleId: 'com.example.employeeCommunicationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAus_o9p2IhKHPnecp3mTQKxxWWf6i2F4',
    appId: '1:46439967773:web:44b669946f3ef2a15b6af4',
    messagingSenderId: '46439967773',
    projectId: 'employee-communication-a-e9d67',
    authDomain: 'employee-communication-a-e9d67.firebaseapp.com',
    storageBucket: 'employee-communication-a-e9d67.firebasestorage.app',
    measurementId: 'G-6WMFL9N7N2',
  );
}
